# TEC - Automated Mismatch Detection Tool
# Copyright 2023 Carnegie Mellon University.
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# Released under a BSD (SEI)-style license, please see license.txt or contact permission@sei.cmu.edu for full terms.
# [DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited distribution.  Please see Copyright notice for non-US Government use and distribution.
# This Software was created using the SEI Design System and includes and/or makes use of Third-Party Software subject to its own license.
# DM23-0003


version: '3.7'

services:
  frontend:
    container_name: frontend
    build: frontend
    ports:
      - '3000:3000'
    env_file:
      - 'proxy.env'
    volumes:
      - ./frontend/assets/css:/frontend/assets/css
      - ./frontend/components:/frontend/components
      - ./frontend/pages:/frontend/pages
      - ./frontend/plugins:/frontend/plugins
      - ./frontend/store:/frontend/store

  api:
    container_name: api
    build: api
    environment:
      - PYTHONBUFFERED=TRUE
    depends_on:
      - postgres
    ports:
      - '3002:80'
    env_file:
      - 'proxy.env'

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./api/db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "3003:5432"
    env_file:
      - "proxy.env"

networks:
  default:
    name: mismatch_default

volumes:
  postgres: